entero= int (input("Intrduce un numero entero "))
decimal= float(input("introduce un numero decimal"))
cadena= str(input("Introduce una cadena"))
bolent=(type(entero))
print(bolent)
print(type(entero))
print(entero)
boldec=(type(decimal))
print(type(decimal))
print(decimal)
bolcad=(type(cadena))
print(type(cadena))
print(cadena)

suma=(decimal+entero)
print(suma)
